# Generated by Django 3.2.9 on 2022-01-04 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0007_auto_20220104_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='poribohonroutes',
            name='imgLink',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
